let hexCores = [] // vetor com o hex de cada cor
let nomesCores = []
let coresEscuras = [1,2,9,13,14,15,16,17,20,22,27,29,31,34,35,41,42,43,44,52,54,56,57,58,60,61,62,63,65,69,70,71,72,73,79,80,81,82,85,86,87,90,92,93,97,98,201,202,203,205,207,211,212,213,217,221,223,224,226]

function criarVetorNomesCor(){
    nomesCores.push(" ")
    nomesCores.push("Red")
    nomesCores.push("Blue")
    nomesCores.push("Green")
    nomesCores.push("Yellow")
    nomesCores.push("Cyan")
    nomesCores.push("Magenta")
    nomesCores.push("Light Green")
    nomesCores.push("Light Grey")
    nomesCores.push("Light Brown")
    nomesCores.push("Light Orange")
    nomesCores.push("Light Yellow")
    nomesCores.push("Light Red")
    nomesCores.push("Dark Grey")
    nomesCores.push("Black")
    nomesCores.push("Brown")
    nomesCores.push("Dark Green")
    nomesCores.push("Dark Red")
    nomesCores.push("White")
    nomesCores.push("Dino Light Red")
    nomesCores.push("Dino Dark Red")
    nomesCores.push("Dino Light Orange")
    nomesCores.push("Dino Dark Orange")
    nomesCores.push("Dino Light Yellow")
    nomesCores.push("Dino Dark Yellow")
    nomesCores.push("Dino Light Green")
    nomesCores.push("Dino Medium Green")
    nomesCores.push("Dino Dark Green")
    nomesCores.push("Dino Light Blue")
    nomesCores.push("Dino Dark Blue")
    nomesCores.push("Dino Light Purple")
    nomesCores.push("Dino Dark Purple")
    nomesCores.push("Dino Light Brown")
    nomesCores.push("Dino Medium Brown")
    nomesCores.push("Dino Dark Brown")
    nomesCores.push("Dino Darker Grey")
    nomesCores.push("Dino Albino")
    nomesCores.push("BigFoot0")
    nomesCores.push("BigFoot4")
    nomesCores.push("BigFoot5")
    nomesCores.push("WolfFur")
    nomesCores.push("DarkWolfFur")
    nomesCores.push("DragonBase0")
    nomesCores.push("DragonBase1")
    nomesCores.push("DragonFire")
    nomesCores.push("DragonGreen0")
    nomesCores.push("DragonGreen1")
    nomesCores.push("DragonGreen2")
    nomesCores.push("DragonGreen3")
    nomesCores.push("WyvernPurple0")
    nomesCores.push("WyvernPurple1")
    nomesCores.push("WyvernBlue0")
    nomesCores.push("WyvernBlue1")
    nomesCores.push("Dino Medium Blue")
    nomesCores.push("Dino Deep Blue")
    nomesCores.push("NearWhite")
    nomesCores.push("NearBlack")
    nomesCores.push("DarkTurquoise")
    nomesCores.push("MediumTurquoise")
    nomesCores.push("Turquoise")
    nomesCores.push("GreenSlate")
    nomesCores.push("Sage")
    nomesCores.push("DarkWarmGray")
    nomesCores.push("MediumWarmGray")
    nomesCores.push("LightWarmGray")
    nomesCores.push("DarkCement")
    nomesCores.push("LightCement")
    nomesCores.push("LightPink")
    nomesCores.push("DeepPink")
    nomesCores.push("DarkViolet")
    nomesCores.push("DarkMagenta")
    nomesCores.push("BurntSienna")
    nomesCores.push("MediumAutumn")
    nomesCores.push("Vermillion")
    nomesCores.push("Coral")
    nomesCores.push("Orange")
    nomesCores.push("Peach")
    nomesCores.push("LightAutumn")
    nomesCores.push("Mustard")
    nomesCores.push("ActualBlack")
    nomesCores.push("MidnightBlue")
    nomesCores.push("DarkBlue")
    nomesCores.push("BlackSands")
    nomesCores.push("LemonLime")
    nomesCores.push("Mint")
    nomesCores.push("Jade")
    nomesCores.push("PineGreen")
    nomesCores.push("SpruceGreen")
    nomesCores.push("LeafGreen")
    nomesCores.push("DarkLavender")
    nomesCores.push("MediumLavender")
    nomesCores.push("Lavender")
    nomesCores.push("DarkTeal")
    nomesCores.push("MediumTeal")
    nomesCores.push("Teal")
    nomesCores.push("PowderBlue")
    nomesCores.push("Glacial")
    nomesCores.push("Cammo")
    nomesCores.push("DryMoss")
    nomesCores.push("Custard")
    nomesCores.push("Cream")
    for(i=0;i<100;i++){
        nomesCores.push(" ")
    }
    nomesCores.push("Black Dye")
    nomesCores.push("Blue Dye")
    nomesCores.push("Brown Dye")
    nomesCores.push("Cyan Dye")
    nomesCores.push("Forest Dye")
    nomesCores.push("Green Dye")
    nomesCores.push("Purple Dye")
    nomesCores.push("Orange Dye")
    nomesCores.push("Parchment Dye")
    nomesCores.push("Pink Dye")
    nomesCores.push("Uncraftable Purple Dye")
    nomesCores.push("Red Dye")
    nomesCores.push("Royalty Dye")
    nomesCores.push("Silver Dye")
    nomesCores.push("Sky Dye")
    nomesCores.push("Tan Dye")
    nomesCores.push("Tangerine Dye")
    nomesCores.push("White Dye")
    nomesCores.push("Yellow Dye")
    nomesCores.push("Magenta Dye")
    nomesCores.push("Brick Dye")
    nomesCores.push("Cantaloupe Dye")
    nomesCores.push("Mud Dye")
    nomesCores.push("Navy Dye")
    nomesCores.push("Olive Dye")
    nomesCores.push("Slate Dye")
    nomesCores.push("227")
    

}

function criarVetorHexCores(){
    hexCores.push(0)
    hexCores.push("#ff0000")
    hexCores.push("#0000ff")
    hexCores.push("#00ff00")
    hexCores.push("#ffff00")
    hexCores.push("#00ffff")
    hexCores.push("#ff00ff")
    hexCores.push("#c0ffba")
    hexCores.push("#c8caca")
    hexCores.push("#786759")
    hexCores.push("#ffb46c")
    hexCores.push("#fffa8a")
    hexCores.push("#ff756c")
    hexCores.push("#7b7b7b")
    hexCores.push("#3b3b3b")
    hexCores.push("#593a2a")
    hexCores.push("#224900")
    hexCores.push("#812118")
    hexCores.push("#ffffff")
    hexCores.push("#ffa8a8")
    hexCores.push("#592b2b")
    hexCores.push("#ffb694")
    hexCores.push("#88532f")
    hexCores.push("#cacaa0")
    hexCores.push("#94946c")
    hexCores.push("#e0ffe0")
    hexCores.push("#799479")
    hexCores.push("#224122")
    hexCores.push("#d9e0ff")
    hexCores.push("#394263")
    hexCores.push("#e4d9ff")
    hexCores.push("#403459")
    hexCores.push("#ffe0ba")
    hexCores.push("#948575")
    hexCores.push("#594e41")
    hexCores.push("#595959")
    hexCores.push("#ffffff")
    hexCores.push("#b79683")
    hexCores.push("#eadad5")
    hexCores.push("#d0a794")
    hexCores.push("#c3b39f")
    hexCores.push("#887666")
    hexCores.push("#a0664b")
    hexCores.push("#cb7956")
    hexCores.push("#bc4f00")
    hexCores.push("#79846c")
    hexCores.push("#909c79")
    hexCores.push("#a5a48b")
    hexCores.push("#74939c")
    hexCores.push("#787496")
    hexCores.push("#b0a2c0")
    hexCores.push("#6281a7")
    hexCores.push("#485c75")
    hexCores.push("#5fa4ea")
    hexCores.push("#4568d4")
    hexCores.push("#ededed")
    hexCores.push("#515151")
    hexCores.push("#184546")
    hexCores.push("#007060")
    hexCores.push("#00c5ab")
    hexCores.push("#40594c")
    hexCores.push("#3e4f40")
    hexCores.push("#3b3938")
    hexCores.push("#585554")
    hexCores.push("#9b9290")
    hexCores.push("#525b56")
    hexCores.push("#8aa196")
    hexCores.push("#e8b0ff")
    hexCores.push("#ff119a")
    hexCores.push("#730046")
    hexCores.push("#b70042")
    hexCores.push("#7e331e")
    hexCores.push("#a93000")
    hexCores.push("#ef3100")
    hexCores.push("#ff5834")
    hexCores.push("#ff7f00")
    hexCores.push("#ffa73a")
    hexCores.push("#ae7000")
    hexCores.push("#949427")
    hexCores.push("#171717")
    hexCores.push("#191d36")
    hexCores.push("#152b3a")
    hexCores.push("#302531")
    hexCores.push("#a8ff44")
    hexCores.push("#38e985")
    hexCores.push("#008840")
    hexCores.push("#0f552e")
    hexCores.push("#005b45")
    hexCores.push("#5b9725")
    hexCores.push("#5b9725") // *** arrumar o hex, 89 darklavender
    hexCores.push("#853587")
    hexCores.push("#bd77be")
    hexCores.push("#0e404a")
    hexCores.push("#105563")
    hexCores.push("#14849c")
    hexCores.push("#82a7ff")
    hexCores.push("#aceaff")
    hexCores.push("#505118")
    hexCores.push("#766e3f")
    hexCores.push("#c0bd5e")
    hexCores.push("#f4ffc0")
    for(i=0;i<100;i++){
        hexCores.push(0)
    }
    hexCores.push("#1f1f1f")
    hexCores.push("#0000ff")
    hexCores.push("#756147")
    hexCores.push("#00ffff")
    hexCores.push("#006c00")
    hexCores.push("#00ff00")
    hexCores.push("#6c00ba")
    hexCores.push("#ff8800")
    hexCores.push("#ffffba")
    hexCores.push("#ff7be1")
    hexCores.push("#7b00e0")
    hexCores.push("#ff0000")
    hexCores.push("#7b00a8")
    hexCores.push("#e0e0e0")
    hexCores.push("#bad4ff")
    hexCores.push("#ffed82")
    hexCores.push("#ad652c")
    hexCores.push("#fefefe")
    hexCores.push("#ffff00")
    hexCores.push("#e71fd9")
    hexCores.push("#94341f")
    hexCores.push("#ff9a00")
    hexCores.push("#473b2b")
    hexCores.push("#34346c")
    hexCores.push("#baba59")
    hexCores.push("#595959")
    hexCores.push("#ffffff")



    // hexCores.push(0)
    // let i = 0
    // while(hexCores.length < 10){
    //     if(coresSujasUn[i] == ':'){
    //         hexCores.push(coresSujasUn[i+2])
    //     }
    // }

    // // for(i=1; i<100; i++){
    // //     let j = 0
    // // }

    
}





/*
'Color ID: 1 Red Hex Code: #ff0000\nColor ID: 2 Blue Hex Code: #0000ff\nColor ID: 3 Green Hex Code: #00ff00\nColor ID: 4 Yellow Hex Code: #ffff00\nColor ID: 5 Cyan Hex Code: #00ffff\nColor ID: 6 Magenta Hex Code: #ff00ff\nColor ID: 7 Light Green Hex Code: #c0ffba\nColor ID: 8 Light Grey Hex Code: #c8caca\nColor ID: 9 Light Brown Hex Code: #786759\nColor ID: 10 Light Orange Hex Code: #ffb46c\nColor ID: 11 Light Yellow Hex Code: #fffa8a\nColor ID: 12 Light Red Hex Code: #ff756c\nColor ID: 13 Dark Grey Hex Code: #7b7b7b\nColor ID: 14 Black Hex Code: #3b3b3b\nColor ID: 15 Brown Hex Code: #593a2a\nColor ID: 16 Dark Green Hex Code: #224900\nColor ID: 17 Dark Red Hex Code: #812118\nColor ID: 18 White Hex Code: #ffffff\nColor ID: 19 Dino Light Red Hex Code: #ffa8a8\nColor ID: 20 Dino Dark Red Hex Code: #592b2b\nColor ID: 21 Dino Light Orange Hex Code: #ffb694\nColor ID: 22 Dino Dark Orange Hex Code: #88532f\nColor ID: 23 Dino Light Yellow Hex Code: #cacaa0\nColor ID: 24 Dino Dark Yellow Hex Code: #94946c\nColor ID: 25 Dino Light Green Hex Code: #e0ffe0\nColor ID: 26 Dino Medium Green Hex Code: #799479\nColor ID: 27 Dino Dark Green Hex Code: #224122\nColor ID: 28 Dino Light Blue Hex Code: #d9e0ff\nColor ID: 29 Dino Dark Blue Hex Code: #394263\nColor ID: 30 Dino Light Purple Hex Code: #e4d9ff\nColor ID: 31 Dino Dark Purple Hex Code: #403459\nColor ID: 32 Dino Light Brown Hex Code: #ffe0ba\nColor ID: 33 Dino Medium Brown Hex Code: #948575\nColor ID: 34 Dino Dark Brown Hex Code: #594e41\nColor ID: 35 Dino Darker Grey Hex Code: #595959\nColor ID: 36 Dino Albino Hex Code: #ffffff\nColor ID: 37 BigFoot0 Hex Code: #b79683\nColor ID: 38 BigFoot4 Hex Code: #eadad5\nColor ID: 39 BigFoot5 Hex Code: #d0a794\nColor ID: 40 WolfFur Hex Code: #c3b39f\nColor ID: 41 DarkWolfFur Hex Code: #887666\nColor ID: 42 DragonBase0 Hex Code: #a0664b\nColor ID: 43 DragonBase1 Hex Code: #cb7956\nColor ID: 44 DragonFire Hex Code: #bc4f00\nColor ID: 45 DragonGreen0 Hex Code: #79846c\nColor ID: 46 DragonGreen1 Hex Code: #909c79\nColor ID: 47 DragonGreen2 Hex Code: #a5a48b\nColor ID: 48 DragonGreen3 Hex Code: #74939c\nColor ID: 49 WyvernPurple0 Hex Code: #787496\nColor ID: 50 WyvernPurple1 Hex Code: #b0a2c0\nColor ID: 51 WyvernBlue0 Hex Code: #6281a7\nColor ID: 52 WyvernBlue1 Hex Code: #485c75\nColor ID: 53 Dino Medium Blue Hex Code: #5fa4ea\nColor ID: 54 Dino Deep Blue Hex Code: #4568d4\nColor ID: 55 NearWhite Hex Code: #ededed\nColor ID: 56 NearBlack Hex Code: #515151\nColor ID: 57 DarkTurquoise Hex Code: #184546\nColor ID: 58 MediumTurquoise Hex Code: #007060\nColor ID: 59 Turquoise Hex Code: #00c5ab\nColor ID: 60 GreenSlate Hex Code: #40594c\nColor ID: 61 Sage Hex Code: #3e4f40\nColor ID: 62 DarkWarmGray Hex Code: #3b3938\nColor ID: 63 MediumWarmGray Hex Code: #585554\nColor ID: 64 LightWarmGray Hex Code: #9b9290\nColor ID: 65 DarkCement Hex Code: #525b56\nColor ID: 66 LightCement Hex Code: #8aa196\nColor ID: 67 LightPink Hex Code: #e8b0ff\nColor ID: 68 DeepPink Hex Code: #ff119a\nColor ID: 69 DarkViolet Hex Code: #730046\nColor ID: 70 DarkMagenta Hex Code: #b70042\nColor ID: 71 BurntSienna Hex Code: #7e331e\nColor ID: 72 MediumAutumn Hex Code: #a93000\nColor ID: 73 Vermillion Hex Code: #ef3100\nColor ID: 74 Coral Hex Code: #ff5834\nColor ID: 75 Orange Hex Code: #ff7f00\nColor ID: 76 Peach Hex Code: #ffa73a\nColor ID: 77 LightAutumn Hex Code: #ae7000\nColor ID: 78 Mustard Hex Code: #949427\nColor ID: 79 ActualBlack Hex Code: #171717\nColor ID: 80 MidnightBlue Hex Code: #191d36\nColor ID: 81 DarkBlue Hex Code: #152b3a\nColor ID: 82 BlackSands Hex Code: #302531\nColor ID: 83 LemonLime Hex Code: #a8ff44\nColor ID: 84 Mint Hex Code: #38e985\nColor ID: 85 Jade Hex Code: #008840\nColor ID: 86 PineGreen Hex Code: #0f552e\nColor ID: 87 SpruceGreen Hex Code: #005b45\nColor ID: 88 LeafGreen Hex Code: #5b9725\nColor ID: 89 DarkLavender Hex Code: #5e275f\nColor ID: 90 MediumLavender Hex Code: #853587\nColor ID: 91 Lavender Hex Code: #bd77be\nColor ID: 92 DarkTeal Hex Code: #0e404a\nColor ID: 93 MediumTeal Hex Code: #105563\nColor ID: 94 Teal Hex Code: #14849c\nColor ID: 95 PowderBlue Hex Code: #82a7ff\nColor ID: 96 Glacial Hex Code: #aceaff\nColor ID: 97 Cammo Hex Code: #505118\nColor ID: 98 DryMoss Hex Code: #766e3f\nColor ID: 99 Custard Hex Code: #c0bd5e\nColor ID: 100 Cream Hex Code: #f4ffc0\n'

*/